---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metabase
  labels:
    app: metabase
    app.kubernetes.io/name: metabase
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/subnets: subnet-0f07f74d367977def,subnet-0721286f3422f0e43
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:826838947101:certificate/7a7e1b08-ddc2-4fe4-9af5-7da1e4ca7086
spec:
  ingressClassName: alb
  rules:
    - host: metabase.qa.lbpay.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: metabase
                port:
                  number: 80
