---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: analytics

resources:
  - namespace.yaml
  - pvc.yaml
  - metabase-db-deployment.yaml
  - metabase-db-service.yaml
  - metabase-deployment.yaml
  - metabase-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: metabase
